@WebApi_HostAddress = http://localhost:5125

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/students
Accept: application/json

###
GET {{WebApi_HostAddress}}/api/students/{{studentId}}
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/students
Content-Type: application/json

{
  "studentId": "",
  "firstName": "Adam",
  "lastName": "Nowak",
  "email": "adam@wsei.edu.pl",
  "programCode": "Informatyka",
  "yearOfStudy": 1,
  "enrollmentYearFrom": 2024
}

###

PUT {{WebApi_HostAddress}}/api/students/{{studentId}}
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak",
  "email": "adam.updated@wsei.edu.pl",
  "programCode": "Informatyka",
  "yearOfStudy": 2,
  "status": 0
}


###

POST {{WebApi_HostAddress}}/api/students/{{studentId}}/grades
Content-Type: application/json

{
  "courseId": "00000000-0000-0000-0000-000000000000",
  "gradeValue": 4,
  "gradeType": 0,
  "lecturerId": null,
  "academicYearId": null,
  "date": "2024-05-01T00:00:00Z"
}


